### ISSUE TITLE
Error when opening a parquet file with VAEX

### ISSUE THREAD

**Issue by mehdimansouri** [vaexio/vaex-talks#1]
Code: 
import vaex as vx
df = vx.open("/Users/admin/Documents/Data/HOT/CA/ca_18_19.parquet")

Error message: 
ERROR:MainThread:vaex:error opening '/Users/admin/Documents/Data/HOT/CA/ca_18_19.parquet'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-834384d570cd> in <module>
----> 1 df = vx.open("/Users/admin/Documents/Data/HOT/CA/ca_18_19.parquet")

/anaconda3/lib/python3.7/site-packages/vaex/__init__.py in open(path, convert, shuffle, copy_index, *args, **kwargs)
    189                         ds = from_csv(path, copy_index=copy_index, **kwargs)
    190                     else:
--> 191                         ds = vaex.file.open(path, *args, **kwargs)
    192                     if convert:
    193                         ds.export_hdf5(filename_hdf5, shuffle=shuffle)

/anaconda3/lib/python3.7/site-packages/vaex/file/__init__.py in open(path, *args, **kwargs)
     28     for opener in opener_classes:
     29         if opener.can_open(path, *args, **kwargs):
---> 30             return opener.open(path, *args, **kwargs)
     31     if hdf5:
     32         openers.extend(hdf5.dataset.dataset_type_map.items())

/anaconda3/lib/python3.7/site-packages/vaex_arrow/opener.py in open(path, *args, **kwargs)
     19     def open(path, *args, **kwargs):
     20         from .dataset import DatasetParquet
---> 21         return DatasetParquet(path, *args, **kwargs)
     22 
     23 def register_opener():

/anaconda3/lib/python3.7/site-packages/vaex_arrow/dataset.py in __init__(self, filename, table, write)
     18         self._write = write
     19         if table is None:
---> 20             self._load()
     21         else:
     22             self._load_table(table)

/anaconda3/lib/python3.7/site-packages/vaex_arrow/dataset.py in _load(self)
     59         # do mmapping later on
     60         table = pq.read_table(self.path)
---> 61         self._load_table(table)
     62 
     63 vaex.file.other.dataset_type_map["arrow"] = DatasetArrow

/anaconda3/lib/python3.7/site-packages/vaex_arrow/dataset.py in _load_table(self, table)
     35             # TODO: keep the arrow columns, and support and test chunks
     36             arrow_array = col.data.chunks[0]
---> 37             column = column_from_arrow_array(arrow_array)
     38 
     39             self.columns[name] = column

/anaconda3/lib/python3.7/site-packages/vaex_arrow/convert.py in column_from_arrow_array(arrow_array)
     36             null_bitmap = np.frombuffer(bitmap_buffer, 'uint8', len(bitmap_buffer))
     37         offsets = np.frombuffer(offsets, np.int32, len(offsets)//4)
---> 38         string_bytes = np.frombuffer(string_bytes, 'S1', len(string_bytes))
     39         column = ColumnStringArrow(offsets, string_bytes, len(arrow_array), null_bitmap=null_bitmap)
     40         return column

TypeError: object of type 'NoneType' has no len()

**Comment by maartenbreddels** [comment]
Hi,

thanks for the report! A better place to put issues about vaex is https://github.com/vaexio/vaex/issues but this is fine for now.
Is there any way you could share this file with me?
I'm surprised this value can be None.

Regards,

Maarten
